export const dummyUsers = [
  {
    name: "Ahmed Khan",
    id: "client-1",
    email: "ahmed.khan@example.com",
    phone: "+971501234567",
    role: "Client",
    status: "active",
    createdAt: "2024-01-15",
    documents: [
      {
        id: "doc-1",
        type: "Emirates ID",
        expiry: "2026-02-15",
        issueDate: "2020-02-15",
        notes: "Valid government ID. Need renewal soon.",
        fileUrls: ["emirates-id.pdf"],
      },
      {
        id: "doc-2",
        type: "Passport",
        expiry: "2026-08-20",
        issueDate: "2016-08-20",
        notes: "Pakistani passport. International travel document.",
        fileUrls: ["passport-front.jpg", "passport-back.jpg"],
      },
      {
        id: "doc-3",
        type: "Visa",
        expiry: "2025-06-30",
        issueDate: "2023-06-30",
        notes: "UAE residence visa. 2-year validity.",
        fileUrls: ["visa-stamp.jpg"],
      },
    ],
  },
  {
    name: "Sara Ali",
    id: "client-2",
    email: "sara.ali@example.com",
    phone: "+971509876543",
    role: "Client",
    status: "active",
    createdAt: "2023-06-20",
    documents: [
      {
        id: "doc-4",
        type: "Trade License",
        expiry: "2026-03-02",
        issueDate: "2024-03-02",
        notes: "Dubai Chamber of Commerce registration.",
        fileUrls: ["trade-license.pdf"],
      },
      {
        id: "doc-5",
        type: "Business Registration",
        expiry: "2026-12-31",
        issueDate: "2024-01-01",
        notes: "Official business registration certificate.",
        fileUrls: ["business-reg.pdf"],
      },
      {
        id: "doc-6",
        type: "Insurance Certificate",
        expiry: "2025-12-15",
        issueDate: "2024-12-15",
        notes: "Commercial insurance policy active.",
        fileUrls: ["insurance.pdf"],
      },
      {
        id: "doc-7",
        type: "Bank Statement",
        expiry: "2025-02-28",
        issueDate: "2025-01-28",
        notes: "January 2025 bank statement for verification.",
        fileUrls: ["bank-statement.pdf"],
      },
    ],
  },
  {
    name: "Rashed LLC",
    id: "client-3",
    email: "contact@rashed-llc.ae",
    phone: "+971504445566",
    role: "Client",
    status: "active",
    createdAt: "2023-03-10",
    documents: [
      {
        id: "doc-8",
        type: "Trade License",
        expiry: "2026-02-18",
        issueDate: "2024-02-18",
        notes: "Main trading license for import/export operations.",
        fileUrls: ["main-trade-license.pdf"],
      },
      {
        id: "doc-9",
        type: "Emirates ID",
        expiry: "2026-02-18",
        issueDate: "2020-02-18",
        notes: "Corporate registration ID.",
        fileUrls: ["corporate-id.pdf"],
      },
      {
        id: "doc-10",
        type: "Tax Certificate",
        expiry: "2025-12-31",
        issueDate: "2024-01-01",
        notes: "VAT registration and tax compliance certificate.",
        fileUrls: ["tax-certificate.pdf"],
      },
      {
        id: "doc-11",
        type: "Audit Report",
        expiry: "2025-08-15",
        issueDate: "2024-08-15",
        notes: "Annual financial audit report 2024.",
        fileUrls: ["audit-report-2024.pdf"],
      },
    ],
  },
];
